### ISSUE TITLE
Another parsing error

### ISSUE THREAD

**Issue by BellandBlackBird** [jdferreira/sleepyjson#2]
I got a a bit further this time, but now encountered this issue:
ValueError: Unexpected input 'sentence_index": 1, "prediction": 0.2800' inside object

**Comment by BellandBlackBird** [comment]
Is this problem starting to explode?

**Comment by jdferreira** [comment]
That is surprising. Is this a different JSON file? I ran the parser on your other input and it seemed to reach the end without issue.

**Comment by BellandBlackBird** [comment]
Yes it is. Shall i send you that object as well? I am however starting to worry a little bit. I have about 1.8 million objects to go through, and the first error i encountered at around position 3800, and this one at 7800.

**Comment by BellandBlackBird** [comment]
hmmm no I got 11000. Hopefully this is a problem on my end. Maybe let's close this issue for now.

**Comment by BellandBlackBird** [comment]
I will get back to you if I make it or it break it :)

**Comment by BellandBlackBird** [comment]
Currently, everything seems to work now. Thank you!

Från: "João D. Ferreira" ***@***.***>
Svara till: jdferreira/sleepyjson ***@***.***>
Datum: måndag 29 mars 2021 18:43
Till: jdferreira/sleepyjson ***@***.***>
Kopia: Björn Alvinge ***@***.***>, Author ***@***.***>
Ämne: Re: [jdferreira/sleepyjson] Another parsing error (#2)


That is surprising. Is this a different JSON file? I ran the parser on your other input and it seemed to reach the end without issue.

**Comment by jdferreira** [comment]
Glad to hear.

Did you understand what caused the problem? Maybe someone else will run into the same issue in the future.

Thanks.

**Comment by BellandBlackBird** [comment]
I think it was just me not restarting my Jupyter notebook after the pip reinstall 😊
Från: "João D. Ferreira" ***@***.***>
Svara till: jdferreira/sleepyjson ***@***.***>
Datum: onsdag 31 mars 2021 13:45
Till: jdferreira/sleepyjson ***@***.***>
Kopia: Björn Alvinge ***@***.***>, State change ***@***.***>
Ämne: Re: [jdferreira/sleepyjson] Another parsing error (#2)


Glad to hear.

Did you understand what caused the problem? Maybe someone else will run into the same issue in the future.

Thanks.
